name: Releases

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set github tag
        id: github
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.17.3'
    - name: Build binary
      env:
        RELEASE_VERSION: ${{ steps.github.outputs.tag }}
      run: |
        ./bin/build.sh
    - uses: ncipollo/release-action@v1
      with:
        artifacts: ".out/decrypter-*"
        token: ${{ secrets.GITHUB_TOKEN }}
